name: Conan

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: ubuntu-22.04
                    conanflags: '-tf conan/test_package/'
                  - os: macos-latest
                    conanflags: ''

        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Install Ubuntu packages
            if: matrix.os == 'ubuntu-22.04'
            run: |
                sudo apt-get install -y gcc g++ cmake wget git python3 python3-pip python3-venv

          - name: Install MacOS packages
            if: matrix.os == 'macos-latest'
            run: |
                brew install postgresql
                brew install libiconv  # https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx

          - name: Install common packages
            run: |
                pip install "conan==2.8.0"
                pip install numpy
                conan profile detect
                conan profile show

          - name: Run conan
            run: |
                conan create . --build=missing -s:a compiler.cppstd=17 -pr:b=default ${{matrix.conanflags}}
