name: CI

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

jobs:
    macos:
        name: MacOS (build only)
        runs-on: macos-latest
        env:
            CMAKE_FLAGS: >-
                -GNinja
                -DCMAKE_BUILD_TYPE=Debug
                -DUSERVER_NO_WERROR=1
                -DUSERVER_BUILD_ALL_COMPONENTS=1
                -DUSERVER_BUILD_SAMPLES=1
                -DUSERVER_BUILD_TESTS=1
                -DUSERVER_FEATURE_REDIS_HI_MALLOC=1
                -DUSERVER_FEATURE_CRYPTOPP_BLAKE2=0
                -DUSERVER_FEATURE_POSTGRESQL=0
                -DUSERVER_FEATURE_GRPC=0
                -DUSERVER_FEATURE_GRPC_REFLECTION=0
                -DUSERVER_FEATURE_OTLP=0
                -DUSERVER_FEATURE_MYSQL=0
                -DUSERVER_FEATURE_RABBITMQ=0
                -DUSERVER_FEATURE_ROCKS=0
                -DUSERVER_FEATURE_KAFKA=0

        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Install brew packages
            run: |
                export SDKROOT="`xcrun --show-sdk-path`"
                brew update
                brew install $(cat scripts/docs/en/deps/macos.md)
                brew install clang-format
                brew install python@3.11
                brew link postgresql@16
                brew upgrade

          - name: Run cmake
            run: |
                cmake -S./ -B./build_debug -DUSERVER_PYTHON_PATH=$(brew --prefix)/bin/python3.11 $CMAKE_FLAGS

          - name: Compile
            run: |
                cmake --build build_debug -j$(nproc) -- -k 1
